### ISSUE TITLE
deepdfa and unixcoder ?

### ISSUE THREAD

**Issue by nss2024** [ISU-PAAL/DeepDFA#9]
hello ?
good to see you again? 

i want using deepdfa output data  -> unixcoder combine 

How can I insert deepdfa data into unixcoder after bit vector processing?

**Comment by huangyuyan3** [comment]
> hello ? good to see you again?
> 
> i want using deepdfa output data -> unixcoder combine
> 
> How can I insert deepdfa data into unixcoder after bit vector processing?

May I ask if you have successfully reproduced it? Can the code in this repository be replicated and does it match the results in the paper?
